config/routes.rb
Desk::Application.routes.draw do
  root 'dashboard#index'

  resources :filters
  resources :cases
  resources :labels

end

app/models/case.rb
class Case < OpenStruct
	include JsonParser
end

app/models/filter.rb
class Filter < OpenStruct

	include JsonParser

	def id
		return nil unless self._links
		link = self._links["self"]["href"]
		link.gsub('/api/v2/filters/', '').try(:to_i)
	end

end

app/models/label.rb
class Label < OpenStruct
	include JsonParser
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cases_controller.rb
class CasesController < ApplicationController

	def index
		opts = {:filter_id => params[:filter_id]} if params[:filter_id]
		response = DESK_CLIENT.cases(opts)
		@cases   = Case.parse_json(response.body)

		response = DESK_CLIENT.filters
		@filters = Filter.parse_json(response.body)
	end

	def edit
		response = DESK_CLIENT.case(params[:id])
		@case    = Case.parse_json(response.body)
		response = DESK_CLIENT.labels
		@labels  = Label.parse_json(response.body)
	end

	def update
		params.delete(:authenticity_token)
		params.merge!(:label_action => 'replace')
		response = DESK_CLIENT.update_case(params[:id], params)

		if ["200","201"].include? response.code
			flash[:notice] = "Case update successfully."
			redirect_to cases_url
		else
			result = JSON.parse(response.body)
			flash[:error] = result["message"]
			return render edit_case_url(params[:id])
		end
	end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

	def index
	end

end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController

	def index
		response = DESK_CLIENT.filters
		@filters = Filter.parse_json(response.body)
	end

end

app/controllers/labels_controller.rb
class LabelsController < ApplicationController

	def index
		response = DESK_CLIENT.labels
		@labels = Label.parse_json(response.body)
	end

	def new

	end

	def create
		params.delete(:authenticity_token)
		response = DESK_CLIENT.create_label(params)

		if ["200","201"].include? response.code
			flash[:notice] = "Label created successfully."
			redirect_to labels_url
		else
			result = JSON.parse(response.body)
			flash[:error] = result["message"]
			return render :new
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cases_helper.rb
module CasesHelper
end

app/views/cases/edit.html.erb
<div class="well">
	<h2><%= @case.subject %></h2>
	<p class="blurb"><%= @case.blurb %></p>

	<h2>Labels</h2>

	<%= form_tag "/cases/#{params[:id]}", :method => :put do %>
		<div class="inner">
			<% @labels.each do |label| %>
				<div class="col-sm-4 case-label">
					<% checked = @case.labels.include?(label.name) ? true : false %>
					<%= check_box_tag "labels[]", label.name, checked %>
					<%= label_tag label.name %>
				</div>
			<% end %>
		</div>
		<div class="submit">
			<%= submit_tag "Save Changes", :class => 'btn btn-primary' %>
		</div>
	<% end %>
</div>

app/views/cases/index.html.erb
<div class="cases">
	<h1>Your Cases</h1>

	<ul id="filters" class="nav nav-pills">

		<% @filters.each do |_filter| %>
			<% active = params[:filter_id].try(:to_i) == _filter.id ? "active" : '' %>
			<li class="filter-<%= _filter.id %> <%= active %>">
				<%= link_to _filter.name, cases_path(:filter_id => _filter.id) %></a>
			</li>
		<% end %>
	</ul>

	<ul id="cases" class="list-group">
		<% @cases.each do |_case| %>
			<% subject = _case.subject.blank? ? "(no subject)" : _case.subject %>
			<li class="case-<%= _case.id %> list-group-item">
				<%= link_to subject, edit_case_path(_case.id) %></a>
				<% if _case.labels %>
					<ul class="labels">
						<% _case.labels.each do |label| %>
							<li class="label label-default"><%= label %></li>
						<% end %>
					</ul>
				<% end %>
			</li>
		<% end %>
	</ul>
</div>

app/views/dashboard/index.html.erb
<div class="dashboard">
        <h1>Welcome to TESTCO</h1>
        <p class="lead">The greatest company there ever was and ever will be.<br> Please click on a menu item to get started.</p>
</div>

app/views/labels/index.html.erb
<div class="labels">
	<h1>Your Labels</h1>

	<%= link_to "Create New Label", new_label_path, :class => 'btn btn-info' %>

	<ul id="labels" class="list-group">
		<% @labels.each do |label| %>
			<li class="label-<%= label.id %> list-group-item">
				<%= label.name %>
			</li>
		<% end %>
	</ul>
</div>

app/views/labels/new.html.erb
<div class="well">
	<h2>New Label</h2>

	<%= form_tag :labels do %>
		<div class="form-group">
			<div class="col-sm-6">
				<%= label_tag :name %>
			</div>
			<div class="col-sm-6">
				<%= text_field_tag :name %>
			</div>
		</div>

		<div class="form-group">
			<div class="description">
				<%= label_tag :description %>
				<%= text_area_tag :description %>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-6">
				<%= label_tag :types %>
			</div>
			<div class="col-sm-6">
				<%= select_tag :types, options_for_select({"Case" => :case, "Macro" => :macro, "Article" => :article}) %>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-6">
				<%= label_tag :enabled %>
			</div>

			<div class="col-sm-6">
				<%= select_tag :enabled, options_for_select({"Enabled" => true, "Disabled" => false}) %>
			</div>
		</div>

		<div class="form-group">
			<div class="col-sm-6">
				<%= label_tag :color %>
			</div>

			<div class="col-sm-6">
				<%= select_tag :color, options_for_select({
					"Default" 	=> :default,
					"Blue" 		=> :blue,
					"White" 	=> :white,
					"Yellow" 	=> :yellow,
					"Red"		=> :red,
					"Orange" 	=> :orange,
					"Green" 	=> :green,
					"Black" 	=> :black,
					"Purple" 	=> :purple,
					"Brown" 	=> :brown,
					"Grey" 		=> :grey,
					"Pink" 		=> :pink
				}) %>
			</div>
		</div>

		<div class="submit">
			<%= submit_tag "Save Changes", :class => 'btn btn-primary' %>
		</div>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Desk</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
        	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
            	<span class="sr-only">Toggle navigation</span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
            	<span class="icon-bar"></span>
          	</button>
          	<%= link_to "Testco", root_path, :class => "navbar-brand" %>

        </div>
        <div class="collapse navbar-collapse">
        	<ul class="nav navbar-nav">
            	<li class="<%= params[:controller] == 'dashboard' ? 'active' : '' %>"><%= link_to "Home", root_path %></li>
            	<li class="<%= params[:controller] == 'cases' ? 'active' : '' %>"><%= link_to "Cases", cases_path %></li>
            	<li class="<%= params[:controller] == 'labels' ? 'active' : '' %>"><%= link_to "Labels", labels_path %></li>
          	</ul>
        </div>
      </div>
    </div>

    <% unless flash[:notice].blank? %>
      <div class="alert alert-success"><%= flash[:notice] %></div>
    <% end %>

    <% unless flash[:error].blank? %>
      <div class="alert alert-danger"><%= flash[:error] %></div>
    <% end %>

    <div class="container">
      <div class="inner-container">
     	  <%= yield %>
      </div>
    </div>

</body>
</html>